---
- hosts: localhost
  tasks:
    - name: Install build essential
      become: true
      ansible.builtin.apt:
        name: ['build-essential']
        state: present
        update_cache: yes
    - name: Install emacs dependencies
      become: true
      ansible.builtin.apt:
        pkg: emacs
        state: build-dep
    
    - name: Checkout emacs
      ansible.builtin.git:
        repo: 'git://git.sv.gnu.org/emacs.git'
        dest: '~/emacs'
    - name: Build emacs
      shell: cd ~/emacs/ && ./autogen.sh && ./configure && make -j2
    - name: Install emacs
      become: true
      shell: cd /home/parallels/emacs && make install
