---
- hosts: localhost
  tasks:
    - name: Install xmonad dependencies
      become: true
      ansible.builtin.apt:
        name: ['libx11-dev', 'libxft-dev', 'libxinerama-dev', 'libxrandr-dev', 'libxss-dev', 'cabal-install']
        state: present
        update_cache: yes
    - name: Checkout xmonad
      ansible.builtin.git:
        repo: 'https://github.com/neovim/neovim'
        dest: '~/.config/xmonad/xmonad'
    - name: Checkout xmonad-contrib
      ansible.builtin.git:
        repo: 'https://github.com/xmonad/xmonad-contrib'
        dest: '~/.config/xmonad/xmonad-contrib'
    - name: Cabal update
      shell: cabal update
    - name: Cabal install xmonad deps
      shell: cabal install --package-env=$HOME/.config/xmonad --lib base xmonad xmonad-contrib
    - name: Cabal install xmonad
      shell: cabal install --package-env=$HOME/.config/xmonad xmonad
